# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20170622_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='fecha_creacion_C',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='fecha_modificacion_C',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='fecha_creacion_N',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='fecha_modificacion_N',
            new_name='fecha_modificacion',
        ),
        migrations.AddField(
            model_name='news',
            name='destacada',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
