# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_auto_20170622_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id_categoria',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='id_noticia',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
